# https://docs.cypress.io/guides/continuous-integration/github-actions
name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Create and save build
  install:
    runs-on: ubuntu-22.04

    timeout-minutes: 5 # Set a timeout of 5 minutes for this job

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build project
        uses: cypress-io/github-action@v5
        with:
          # Disable running of tests within install job
          runTests: false
          build: yarn build-react

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: build

  e2e:
    runs-on: ubuntu-22.04
    needs: install

    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folder
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Cypress run e2e tests
        # Uses the official Cypress GitHub action https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v5
        with:
          # Starts web server for E2E tests - replace with your own server invocation
          # https://docs.cypress.io/guides/continuous-integration/introduction#Boot-your-server
          start: yarn serve --port 3000
          wait-on: "http://localhost:3000" # Waits for above
          # Runs on chrome
          browser: chrome

  component:
    runs-on: ubuntu-latest
    needs: install

    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folder
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Cypress run component tests
        # Uses the official Cypress GitHub action https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v5
        with:
          # Starts web server for E2E tests - replace with your own server invocation
          # https://docs.cypress.io/guides/continuous-integration/introduction#Boot-your-server
          start: yarn serve --port 3000
          wait-on: "http://localhost:3000" # Waits for above
          # Run on chrome
          browser: chrome
          # Only include component tests
          component: true

  jest:
    runs-on: ubuntu-latest
    needs: install

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folder
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Jest run tests
        run: yarn test
